labels:
  - name: "🐛 Bug"
    color: "6cc644" # Light green
    description: "Something isn't working"
  
  - name: "✨ Feature Request"
    color: "ffeb3b" # Light yellow
    description: "Request for a new feature"

  - name: "🛠️ Enhancement"
    color: "d2b48c" # Light brown/tan
    description: "Improvement to an existing feature"

  - name: "📚 Documentation"
    color: "00cfff" # Cyan
    description: "Improvements or additions to documentation"

  - name: "❓ Question"
    color: "e1bee7" # Light purple
    description: "Further information is requested"

  - name: "🚀 Performance"
    color: "ffffff" # White
    description: "Performance-related issues or enhancements"

  - name: "🔍 Investigation"
    color: "b3e5fc" # Light blue
    description: "Further research or exploration is needed"

  - name: "⚠️ Deprecated"
    color: "fff176" # Light yellow, as you wanted deprecated to be yellow as well
    description: "Feature or functionality is being deprecated"

  - name: "🔴 Critical"
    color: "ff1744" # Bright red
    description: "Top priority issue"
