- name: "🐛 Bug"
  color: "6cc644"
  description: "Something isn't working"
- name: "✨ Feature Request"
  color: "ffeb3b"
  description: "Request for a new feature"
- name: "🛠️ Enhancement"
  color: "d2b48c"
  description: "Improvement to an existing feature"
- name: "📚 Documentation"
  color: "00cfff"
  description: "Improvements or additions to documentation"
- name: "❓ Question"
  color: "e1bee7"
  description: "Further information is requested"
- name: "🚀 Performance"
  color: "ffffff"
  description: "Performance-related issues or enhancements"
- name: "🔍 Investigation"
  color: "b3e5fc"
  description: "Further research or exploration is needed"
- name: "⚠️ Deprecated"
  color: "fff176"
  description: "Feature or functionality is being deprecated"
- name: "🔴 Critical"
  color: "ff1744"
  description: "Top priority issue"
- name: "❌ Invalid"
  color: "000000"
  description: "No"