blank_issues_enabled: false
contact_links:
  - name: "❓ Question or Support"
    url: https://github.com/Digital39999/ts-prisma/discussions/new?category=q-a
    about: "Ask a question about using ts-prisma or request support for a specific issue."
