name: ❓ Question or Support
description: Ask a question about using `ts-prisma` or request support for a specific issue.
title: "[QUESTION] "
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Need help with `ts-prisma`? Please provide details about your question or issue.
  - type: input
    id: question
    attributes:
      label: Your Question
      description: Clearly state your question or the problem you're facing.
    validations:
      required: true
  - type: textarea
    id: code_snippet
    attributes:
      label: Code Snippet
      description: Include a code snippet or relevant part of your Prisma schema that relates to your question.
    validations:
      required: false
  - type: input
    id: expected_behavior
    attributes:
      label: Expected vs Actual Behavior
      description: Describe what you expected to happen and what actually happened.
    validations:
      required: false
  - type: dropdown
    id: node_version
    attributes:
      label: Node.js Version
      description: Select the Node.js version you're using.
      options:
        - 20.x
        - 22.x
        - Other
  - type: input
    id: prisma_version
    attributes:
      label: Prisma Version
      description: Provide the Prisma version you're using.
  - type: input
    id: ts_prisma_version
    attributes:
      label: ts-prisma Version
      description: Provide the version of `ts-prisma` you're using.
  - type: input
    id: typescript_version
    attributes:
      label: TypeScript Version
      description: Provide the TypeScript version you're using.
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other relevant information or context.
